// <auto-generated />
using System;
using IERIC.SumariosIERIC.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(SumariosContext))]
    [Migration("20260728202448_AddQuizPersistence")]
    partial class AddQuizPersistence
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("IERIC.SumariosIERIC.Domain.Entities.Empresa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<long?>("Cuit")
                        .HasColumnType("bigint");

                    b.Property<bool>("EsCooperativa")
                        .HasColumnType("bit");

                    b.Property<bool>("EstadoActivo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaAlta")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaUpdate")
                        .HasColumnType("datetime2");

                    b.Property<int>("LegacyId")
                        .HasColumnType("int");

                    b.Property<string>("RazonSocial")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsuarioAlta")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsuarioUpdate")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Empresa", "dbo");
                });

            modelBuilder.Entity("IERIC.SumariosIERIC.Infrastructure.Persistence.Quiz.QuizCuilVinculadoEntity", b =>
                {
                    b.Property<Guid>("QuizId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Cuil")
                        .HasMaxLength(11)
                        .HasColumnType("char(11)")
                        .IsFixedLength();

                    b.HasKey("QuizId", "Cuil");

                    b.ToTable("QuizCuilVinculado", (string)null);
                });

            modelBuilder.Entity("IERIC.SumariosIERIC.Infrastructure.Persistence.Quiz.QuizDesafioEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("EsActual")
                        .HasColumnType("bit");

                    b.Property<int>("Escenario")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCreacionUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("Numero")
                        .HasColumnType("int");

                    b.Property<Guid>("QuizId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("QuizId")
                        .IsUnique()
                        .HasDatabaseName("UX_QuizDesafio_Quiz_Actual")
                        .HasFilter("[EsActual] = 1");

                    b.HasIndex("QuizId", "Numero")
                        .IsUnique()
                        .HasDatabaseName("UX_QuizDesafio_Quiz_Numero");

                    b.ToTable("QuizDesafio", (string)null);
                });

            modelBuilder.Entity("IERIC.SumariosIERIC.Infrastructure.Persistence.Quiz.QuizOpcionEntity", b =>
                {
                    b.Property<Guid>("QuizDesafioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Id")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Cuil")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("char(11)")
                        .IsFixedLength();

                    b.Property<bool>("EsVinculado")
                        .HasColumnType("bit");

                    b.Property<int>("Orden")
                        .HasColumnType("int");

                    b.HasKey("QuizDesafioId", "Id");

                    b.HasIndex("QuizDesafioId", "Orden")
                        .IsUnique()
                        .HasDatabaseName("UX_QuizOpcion_Desafio_Orden");

                    b.ToTable("QuizOpcion", (string)null);
                });

            modelBuilder.Entity("IERIC.SumariosIERIC.Infrastructure.Persistence.Quiz.QuizRespuestaEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("EsCorrecta")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaRespuestaUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("OpcionesSeleccionadas")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("QuizDesafioId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("QuizDesafioId", "FechaRespuestaUtc")
                        .HasDatabaseName("IX_QuizRespuesta_Desafio_Fecha");

                    b.ToTable("QuizRespuesta", (string)null);
                });

            modelBuilder.Entity("IERIC.SumariosIERIC.Infrastructure.Persistence.Quiz.QuizSesionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CuitEmpresa")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("char(11)")
                        .IsFixedLength();

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCreacionUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaExpiracionUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaFinalizacionUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("IntentosRestantes")
                        .HasColumnType("int");

                    b.Property<int>("IntentosTotales")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CuitEmpresa")
                        .HasDatabaseName("IX_QuizSesion_CuitEmpresa");

                    b.HasIndex("Estado")
                        .HasDatabaseName("IX_QuizSesion_Estado");

                    b.ToTable("QuizSesion", (string)null);
                });

            modelBuilder.Entity("IERIC.SumariosIERIC.Infrastructure.Persistence.Quiz.QuizCuilVinculadoEntity", b =>
                {
                    b.HasOne("IERIC.SumariosIERIC.Infrastructure.Persistence.Quiz.QuizSesionEntity", "Quiz")
                        .WithMany("CuilesVinculados")
                        .HasForeignKey("QuizId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Quiz");
                });

            modelBuilder.Entity("IERIC.SumariosIERIC.Infrastructure.Persistence.Quiz.QuizDesafioEntity", b =>
                {
                    b.HasOne("IERIC.SumariosIERIC.Infrastructure.Persistence.Quiz.QuizSesionEntity", "Quiz")
                        .WithMany("Desafios")
                        .HasForeignKey("QuizId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Quiz");
                });

            modelBuilder.Entity("IERIC.SumariosIERIC.Infrastructure.Persistence.Quiz.QuizOpcionEntity", b =>
                {
                    b.HasOne("IERIC.SumariosIERIC.Infrastructure.Persistence.Quiz.QuizDesafioEntity", "Desafio")
                        .WithMany("Opciones")
                        .HasForeignKey("QuizDesafioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Desafio");
                });

            modelBuilder.Entity("IERIC.SumariosIERIC.Infrastructure.Persistence.Quiz.QuizRespuestaEntity", b =>
                {
                    b.HasOne("IERIC.SumariosIERIC.Infrastructure.Persistence.Quiz.QuizDesafioEntity", "Desafio")
                        .WithMany("Respuestas")
                        .HasForeignKey("QuizDesafioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Desafio");
                });

            modelBuilder.Entity("IERIC.SumariosIERIC.Infrastructure.Persistence.Quiz.QuizDesafioEntity", b =>
                {
                    b.Navigation("Opciones");

                    b.Navigation("Respuestas");
                });

            modelBuilder.Entity("IERIC.SumariosIERIC.Infrastructure.Persistence.Quiz.QuizSesionEntity", b =>
                {
                    b.Navigation("CuilesVinculados");

                    b.Navigation("Desafios");
                });
#pragma warning restore 612, 618
        }
    }
}
