// <auto-generated />
using System;
using IERIC.SumariosIERIC.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(SumariosContext))]
    [Migration("20260928155540_InitialQuizPersistence")]
    partial class InitialQuizPersistence
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("IERIC.SumariosIERIC.Infrastructure.Persistence.Quiz.QuizCuilVinculadoEntity", b =>
                {
                    b.Property<long>("QuizSesionId")
                        .HasColumnType("bigint");

                    b.Property<long>("Cuil")
                        .HasColumnType("bigint");

                    b.HasKey("QuizSesionId", "Cuil")
                        .HasName("PK_QuizCuilVinculado");

                    b.ToTable("QuizCuilVinculado", "dbo");
                });

            modelBuilder.Entity("IERIC.SumariosIERIC.Infrastructure.Persistence.Quiz.QuizDesafioEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("EsActual")
                        .HasColumnType("bit");

                    b.Property<byte>("Escenario")
                        .HasColumnType("tinyint");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime");

                    b.Property<byte>("Numero")
                        .HasColumnType("tinyint");

                    b.Property<long>("QuizSesionId")
                        .HasColumnType("bigint");

                    b.HasKey("Id")
                        .HasName("PK_QuizDesafio");

                    b.HasIndex("QuizSesionId")
                        .IsUnique()
                        .HasDatabaseName("UX_QuizDesafio_Sesion_Actual")
                        .HasFilter("[EsActual] = 1");

                    b.HasIndex("QuizSesionId", "Numero")
                        .IsUnique()
                        .HasDatabaseName("UX_QuizDesafio_Sesion_Numero");

                    b.ToTable("QuizDesafio", "dbo", t =>
                        {
                            t.HasCheckConstraint("CK_QuizDesafio_Escenario", "[Escenario] BETWEEN 1 AND 4");

                            t.HasCheckConstraint("CK_QuizDesafio_Numero", "[Numero] > 0");
                        });
                });

            modelBuilder.Entity("IERIC.SumariosIERIC.Infrastructure.Persistence.Quiz.QuizOpcionEntity", b =>
                {
                    b.Property<long>("QuizDesafioId")
                        .HasColumnType("bigint");

                    b.Property<byte>("CodigoOpcion")
                        .HasColumnType("tinyint");

                    b.Property<long?>("Cuil")
                        .HasColumnType("bigint");

                    b.Property<bool>("EsVinculado")
                        .HasColumnType("bit");

                    b.HasKey("QuizDesafioId", "CodigoOpcion")
                        .HasName("PK_QuizOpcion");

                    b.ToTable("QuizOpcion", "dbo", t =>
                        {
                            t.HasCheckConstraint("CK_QuizOpcion_Codigo", "[CodigoOpcion] BETWEEN 0 AND 5");

                            t.HasCheckConstraint("CK_QuizOpcion_Cuil", "(\r\n                            (\r\n                                [CodigoOpcion] BETWEEN 0 AND 3\r\n                                AND [Cuil] IS NOT NULL\r\n                            )\r\n                            OR\r\n                            (\r\n                                [CodigoOpcion] BETWEEN 4 AND 5\r\n                                AND [Cuil] IS NULL\r\n                            )\r\n                        )");
                        });
                });

            modelBuilder.Entity("IERIC.SumariosIERIC.Infrastructure.Persistence.Quiz.QuizRespuestaEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("EsCorrecta")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaRespuesta")
                        .HasColumnType("datetime");

                    b.Property<long>("QuizDesafioId")
                        .HasColumnType("bigint");

                    b.HasKey("Id")
                        .HasName("PK_QuizRespuesta");

                    b.HasAlternateKey("QuizDesafioId")
                        .HasName("UX_QuizRespuesta_QuizDesafio");

                    b.HasAlternateKey("Id", "QuizDesafioId")
                        .HasName("AK_QuizRespuesta_Id_QuizDesafioId");

                    b.ToTable("QuizRespuesta", "dbo");
                });

            modelBuilder.Entity("IERIC.SumariosIERIC.Infrastructure.Persistence.Quiz.QuizRespuestaOpcionEntity", b =>
                {
                    b.Property<long>("QuizRespuestaId")
                        .HasColumnType("bigint");

                    b.Property<byte>("CodigoOpcion")
                        .HasColumnType("tinyint");

                    b.Property<long>("QuizDesafioId")
                        .HasColumnType("bigint");

                    b.HasKey("QuizRespuestaId", "CodigoOpcion")
                        .HasName("PK_QuizRespuestaOpcion");

                    b.HasIndex("QuizDesafioId", "CodigoOpcion");

                    b.HasIndex("QuizRespuestaId", "QuizDesafioId");

                    b.ToTable("QuizRespuestaOpcion", "dbo");
                });

            modelBuilder.Entity("IERIC.SumariosIERIC.Infrastructure.Persistence.Quiz.QuizSesionEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("BloqueadoHasta")
                        .HasColumnType("datetime");

                    b.Property<long>("CuitEmpresa")
                        .HasColumnType("bigint");

                    b.Property<byte>("Estado")
                        .HasColumnType("tinyint");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("FechaExpiracion")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("FechaFinalizacion")
                        .HasColumnType("datetime");

                    b.Property<byte>("IntentosTotales")
                        .HasColumnType("tinyint");

                    b.Property<string>("UsuarioId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id")
                        .HasName("PK_QuizSesion");

                    b.HasIndex("UsuarioId", "FechaCreacion")
                        .HasDatabaseName("IX_QuizSesion_Usuario_Fecha");

                    b.HasIndex("CuitEmpresa", "Estado", "BloqueadoHasta")
                        .HasDatabaseName("IX_QuizSesion_Cuit_Bloqueo");

                    b.ToTable("QuizSesion", "dbo", t =>
                        {
                            t.HasCheckConstraint("CK_QuizSesion_Estado", "[Estado] BETWEEN 1 AND 4");

                            t.HasCheckConstraint("CK_QuizSesion_IntentosTotales", "[IntentosTotales] > 0");
                        });
                });

            modelBuilder.Entity("IERIC.SumariosIERIC.Infrastructure.Persistence.Quiz.QuizCuilVinculadoEntity", b =>
                {
                    b.HasOne("IERIC.SumariosIERIC.Infrastructure.Persistence.Quiz.QuizSesionEntity", "QuizSesion")
                        .WithMany("CuilesVinculados")
                        .HasForeignKey("QuizSesionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_QuizCuilVinculado_QuizSesion_QuizSesionId");

                    b.Navigation("QuizSesion");
                });

            modelBuilder.Entity("IERIC.SumariosIERIC.Infrastructure.Persistence.Quiz.QuizDesafioEntity", b =>
                {
                    b.HasOne("IERIC.SumariosIERIC.Infrastructure.Persistence.Quiz.QuizSesionEntity", "QuizSesion")
                        .WithMany("Desafios")
                        .HasForeignKey("QuizSesionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_QuizDesafio_QuizSesion_QuizSesionId");

                    b.Navigation("QuizSesion");
                });

            modelBuilder.Entity("IERIC.SumariosIERIC.Infrastructure.Persistence.Quiz.QuizOpcionEntity", b =>
                {
                    b.HasOne("IERIC.SumariosIERIC.Infrastructure.Persistence.Quiz.QuizDesafioEntity", "Desafio")
                        .WithMany("Opciones")
                        .HasForeignKey("QuizDesafioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_QuizOpcion_QuizDesafio_QuizDesafioId");

                    b.Navigation("Desafio");
                });

            modelBuilder.Entity("IERIC.SumariosIERIC.Infrastructure.Persistence.Quiz.QuizRespuestaEntity", b =>
                {
                    b.HasOne("IERIC.SumariosIERIC.Infrastructure.Persistence.Quiz.QuizDesafioEntity", "Desafio")
                        .WithOne("Respuesta")
                        .HasForeignKey("IERIC.SumariosIERIC.Infrastructure.Persistence.Quiz.QuizRespuestaEntity", "QuizDesafioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_QuizRespuesta_QuizDesafio_QuizDesafioId");

                    b.Navigation("Desafio");
                });

            modelBuilder.Entity("IERIC.SumariosIERIC.Infrastructure.Persistence.Quiz.QuizRespuestaOpcionEntity", b =>
                {
                    b.HasOne("IERIC.SumariosIERIC.Infrastructure.Persistence.Quiz.QuizOpcionEntity", "Opcion")
                        .WithMany("RespuestasSeleccionadas")
                        .HasForeignKey("QuizDesafioId", "CodigoOpcion")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_QuizRespuestaOpcion_QuizOpcion");

                    b.HasOne("IERIC.SumariosIERIC.Infrastructure.Persistence.Quiz.QuizRespuestaEntity", "Respuesta")
                        .WithMany("OpcionesSeleccionadas")
                        .HasForeignKey("QuizRespuestaId", "QuizDesafioId")
                        .HasPrincipalKey("Id", "QuizDesafioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_QuizRespuestaOpcion_QuizRespuesta");

                    b.Navigation("Opcion");

                    b.Navigation("Respuesta");
                });

            modelBuilder.Entity("IERIC.SumariosIERIC.Infrastructure.Persistence.Quiz.QuizDesafioEntity", b =>
                {
                    b.Navigation("Opciones");

                    b.Navigation("Respuesta");
                });

            modelBuilder.Entity("IERIC.SumariosIERIC.Infrastructure.Persistence.Quiz.QuizOpcionEntity", b =>
                {
                    b.Navigation("RespuestasSeleccionadas");
                });

            modelBuilder.Entity("IERIC.SumariosIERIC.Infrastructure.Persistence.Quiz.QuizRespuestaEntity", b =>
                {
                    b.Navigation("OpcionesSeleccionadas");
                });

            modelBuilder.Entity("IERIC.SumariosIERIC.Infrastructure.Persistence.Quiz.QuizSesionEntity", b =>
                {
                    b.Navigation("CuilesVinculados");

                    b.Navigation("Desafios");
                });
#pragma warning restore 612, 618
        }
    }
}
