// <auto-generated />
using System;
using IERIC.SumariosIERIC.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(SumariosContext))]
    partial class SumariosContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("IERIC.SumariosIERIC.Infrastructure.Persistence.Inscripcion.EmpresaEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit")
                        .HasColumnOrder(6);

                    b.Property<string>("Calle")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnOrder(11)
                        .HasDefaultValueSql("''");

                    b.Property<string>("CodigoPostal")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnOrder(15)
                        .HasDefaultValueSql("''");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(254)
                        .HasColumnType("varchar(254)")
                        .HasColumnOrder(18)
                        .HasDefaultValueSql("''");

                    b.Property<long>("Cuit")
                        .HasColumnType("bigint")
                        .HasColumnOrder(2);

                    b.Property<bool>("DDJJ")
                        .HasColumnType("bit")
                        .HasColumnOrder(23);

                    b.Property<string>("DeptoOficina")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnOrder(14);

                    b.Property<bool>("EsCooperativa")
                        .HasColumnType("bit")
                        .HasColumnOrder(3);

                    b.Property<bool>("EstadoActivo")
                        .HasColumnType("bit")
                        .HasColumnOrder(4);

                    b.Property<DateTime>("Fa")
                        .HasColumnType("datetime2(7)")
                        .HasColumnName("fa")
                        .HasColumnOrder(7);

                    b.Property<DateTime>("Fm")
                        .HasColumnType("datetime2(7)")
                        .HasColumnName("fm")
                        .HasColumnOrder(9);

                    b.Property<int>("IdActividadsolicitud")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(20)
                        .HasDefaultValueSql("''");

                    b.Property<int>("IdCaracter")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(21)
                        .HasDefaultValueSql("''");

                    b.Property<int>("IdTipoSoc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(22)
                        .HasDefaultValueSql("''");

                    b.Property<int>("LegacyId")
                        .HasColumnType("int")
                        .HasColumnOrder(5);

                    b.Property<string>("Localidad")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnOrder(17)
                        .HasDefaultValueSql("''");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnOrder(12)
                        .HasDefaultValueSql("''");

                    b.Property<byte?>("Piso")
                        .HasColumnType("tinyint")
                        .HasColumnOrder(13);

                    b.Property<string>("Provincia")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnOrder(16)
                        .HasDefaultValueSql("''");

                    b.Property<string>("RazonSocial")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnOrder(1);

                    b.Property<string>("Telefono")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnOrder(19);

                    b.Property<string>("Ua")
                        .HasMaxLength(23)
                        .HasColumnType("varchar(23)")
                        .HasColumnName("ua")
                        .HasColumnOrder(8);

                    b.Property<string>("Um")
                        .HasMaxLength(23)
                        .HasColumnType("varchar(23)")
                        .HasColumnName("um")
                        .HasColumnOrder(10);

                    b.HasKey("Id")
                        .HasName("PK_Empresa");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("Id"));

                    b.HasIndex("Cuit")
                        .IsUnique()
                        .HasDatabaseName("UX_Empresa_Cuit");

                    b.ToTable("Empresa", "dbo");
                });

            modelBuilder.Entity("IERIC.SumariosIERIC.Infrastructure.Persistence.Inscripcion.EmpresaIntegranteEntity", b =>
                {
                    b.Property<long>("IdEmpresa")
                        .HasColumnType("bigint");

                    b.Property<long>("IdEmpresaIntegrante")
                        .HasColumnType("bigint");

                    b.HasKey("IdEmpresa", "IdEmpresaIntegrante")
                        .HasName("PK_EmpresasCuit");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("IdEmpresa", "IdEmpresaIntegrante"));

                    b.ToTable("EmpresasCuit", "dbo");
                });

            modelBuilder.Entity("IERIC.SumariosIERIC.Infrastructure.Persistence.Inscripcion.SolicitudInscripcionEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Comentarios")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Fa")
                        .HasColumnType("datetime")
                        .HasColumnName("fa");

                    b.Property<DateTime?>("Fm")
                        .HasColumnType("datetime")
                        .HasColumnName("fm");

                    b.Property<long>("Idempresa")
                        .HasColumnType("bigint");

                    b.Property<string>("Ua")
                        .HasMaxLength(23)
                        .HasColumnType("varchar(23)")
                        .HasColumnName("ua");

                    b.Property<string>("Um")
                        .HasMaxLength(23)
                        .HasColumnType("varchar(23)")
                        .HasColumnName("um");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id")
                        .HasName("PK_SolInscEmprDig");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("Id"));

                    b.ToTable("SolicitudInscripcionDigitalEmpresaria", "dbo");
                });

            modelBuilder.Entity("IERIC.SumariosIERIC.Infrastructure.Persistence.Quiz.QuizCuilVinculadoEntity", b =>
                {
                    b.Property<long>("QuizSesionId")
                        .HasColumnType("bigint");

                    b.Property<long>("Cuil")
                        .HasColumnType("bigint");

                    b.HasKey("QuizSesionId", "Cuil")
                        .HasName("PK_QuizCuilVinculado");

                    b.ToTable("QuizCuilVinculado", "dbo");
                });

            modelBuilder.Entity("IERIC.SumariosIERIC.Infrastructure.Persistence.Quiz.QuizDesafioEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("EsActual")
                        .HasColumnType("bit");

                    b.Property<byte>("Escenario")
                        .HasColumnType("tinyint");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime");

                    b.Property<byte>("Numero")
                        .HasColumnType("tinyint");

                    b.Property<long>("QuizSesionId")
                        .HasColumnType("bigint");

                    b.HasKey("Id")
                        .HasName("PK_QuizDesafio");

                    b.HasIndex("QuizSesionId")
                        .IsUnique()
                        .HasDatabaseName("UX_QuizDesafio_Sesion_Actual")
                        .HasFilter("[EsActual] = 1");

                    b.HasIndex("QuizSesionId", "Numero")
                        .IsUnique()
                        .HasDatabaseName("UX_QuizDesafio_Sesion_Numero");

                    b.ToTable("QuizDesafio", "dbo", t =>
                        {
                            t.HasCheckConstraint("CK_QuizDesafio_Escenario", "[Escenario] BETWEEN 1 AND 4");

                            t.HasCheckConstraint("CK_QuizDesafio_Numero", "[Numero] > 0");
                        });
                });

            modelBuilder.Entity("IERIC.SumariosIERIC.Infrastructure.Persistence.Quiz.QuizOpcionEntity", b =>
                {
                    b.Property<long>("QuizDesafioId")
                        .HasColumnType("bigint");

                    b.Property<byte>("CodigoOpcion")
                        .HasColumnType("tinyint");

                    b.Property<long?>("Cuil")
                        .HasColumnType("bigint");

                    b.Property<bool>("EsVinculado")
                        .HasColumnType("bit");

                    b.HasKey("QuizDesafioId", "CodigoOpcion")
                        .HasName("PK_QuizOpcion");

                    b.ToTable("QuizOpcion", "dbo", t =>
                        {
                            t.HasCheckConstraint("CK_QuizOpcion_Codigo", "[CodigoOpcion] BETWEEN 0 AND 5");

                            t.HasCheckConstraint("CK_QuizOpcion_Cuil", "(\r\n                            (\r\n                                [CodigoOpcion] BETWEEN 0 AND 3\r\n                                AND [Cuil] IS NOT NULL\r\n                            )\r\n                            OR\r\n                            (\r\n                                [CodigoOpcion] BETWEEN 4 AND 5\r\n                                AND [Cuil] IS NULL\r\n                            )\r\n                        )");
                        });
                });

            modelBuilder.Entity("IERIC.SumariosIERIC.Infrastructure.Persistence.Quiz.QuizRespuestaEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("EsCorrecta")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaRespuesta")
                        .HasColumnType("datetime");

                    b.Property<long>("QuizDesafioId")
                        .HasColumnType("bigint");

                    b.HasKey("Id")
                        .HasName("PK_QuizRespuesta");

                    b.HasAlternateKey("QuizDesafioId")
                        .HasName("UX_QuizRespuesta_QuizDesafio");

                    b.HasAlternateKey("Id", "QuizDesafioId")
                        .HasName("AK_QuizRespuesta_Id_QuizDesafioId");

                    b.ToTable("QuizRespuesta", "dbo");
                });

            modelBuilder.Entity("IERIC.SumariosIERIC.Infrastructure.Persistence.Quiz.QuizRespuestaOpcionEntity", b =>
                {
                    b.Property<long>("QuizRespuestaId")
                        .HasColumnType("bigint");

                    b.Property<byte>("CodigoOpcion")
                        .HasColumnType("tinyint");

                    b.Property<long>("QuizDesafioId")
                        .HasColumnType("bigint");

                    b.HasKey("QuizRespuestaId", "CodigoOpcion")
                        .HasName("PK_QuizRespuestaOpcion");

                    b.ToTable("QuizRespuestaOpcion", "dbo");
                });

            modelBuilder.Entity("IERIC.SumariosIERIC.Infrastructure.Persistence.Quiz.QuizSesionEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("BloqueadoHasta")
                        .HasColumnType("datetime");

                    b.Property<long>("CuitEmpresa")
                        .HasColumnType("bigint");

                    b.Property<byte>("Estado")
                        .HasColumnType("tinyint");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("FechaExpiracion")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("FechaFinalizacion")
                        .HasColumnType("datetime");

                    b.Property<byte>("IntentosTotales")
                        .HasColumnType("tinyint");

                    b.Property<string>("UsuarioId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id")
                        .HasName("PK_QuizSesion");

                    b.HasIndex("UsuarioId", "FechaCreacion")
                        .HasDatabaseName("IX_QuizSesion_Usuario_Fecha");

                    b.HasIndex("CuitEmpresa", "Estado", "BloqueadoHasta")
                        .HasDatabaseName("IX_QuizSesion_Cuit_Bloqueo");

                    b.ToTable("QuizSesion", "dbo", t =>
                        {
                            t.HasCheckConstraint("CK_QuizSesion_Estado", "[Estado] BETWEEN 1 AND 4");

                            t.HasCheckConstraint("CK_QuizSesion_IntentosTotales", "[IntentosTotales] > 0");
                        });
                });

            modelBuilder.Entity("IERIC.SumariosIERIC.Infrastructure.Persistence.Inscripcion.EmpresaIntegranteEntity", b =>
                {
                    b.HasOne("IERIC.SumariosIERIC.Infrastructure.Persistence.Inscripcion.EmpresaEntity", null)
                        .WithMany()
                        .HasForeignKey("IdEmpresa")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_EmpresasCuit_EmpresaPrincipal");

                    b.HasOne("IERIC.SumariosIERIC.Infrastructure.Persistence.Inscripcion.EmpresaEntity", null)
                        .WithMany()
                        .HasForeignKey("IdEmpresaIntegrante")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_EmpresasCuit_EmpresaIntegrante");
                });

            modelBuilder.Entity("IERIC.SumariosIERIC.Infrastructure.Persistence.Inscripcion.SolicitudInscripcionEntity", b =>
                {
                    b.HasOne("IERIC.SumariosIERIC.Infrastructure.Persistence.Inscripcion.EmpresaEntity", null)
                        .WithMany()
                        .HasForeignKey("Idempresa")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_SolInscEmprDig_Empresa");
                });

            modelBuilder.Entity("IERIC.SumariosIERIC.Infrastructure.Persistence.Quiz.QuizCuilVinculadoEntity", b =>
                {
                    b.HasOne("IERIC.SumariosIERIC.Infrastructure.Persistence.Quiz.QuizSesionEntity", "QuizSesion")
                        .WithMany("CuilesVinculados")
                        .HasForeignKey("QuizSesionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_QuizCuilVinculado_QuizSesion_QuizSesionId");

                    b.Navigation("QuizSesion");
                });

            modelBuilder.Entity("IERIC.SumariosIERIC.Infrastructure.Persistence.Quiz.QuizDesafioEntity", b =>
                {
                    b.HasOne("IERIC.SumariosIERIC.Infrastructure.Persistence.Quiz.QuizSesionEntity", "QuizSesion")
                        .WithMany("Desafios")
                        .HasForeignKey("QuizSesionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_QuizDesafio_QuizSesion_QuizSesionId");

                    b.Navigation("QuizSesion");
                });

            modelBuilder.Entity("IERIC.SumariosIERIC.Infrastructure.Persistence.Quiz.QuizOpcionEntity", b =>
                {
                    b.HasOne("IERIC.SumariosIERIC.Infrastructure.Persistence.Quiz.QuizDesafioEntity", "Desafio")
                        .WithMany("Opciones")
                        .HasForeignKey("QuizDesafioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_QuizOpcion_QuizDesafio_QuizDesafioId");

                    b.Navigation("Desafio");
                });

            modelBuilder.Entity("IERIC.SumariosIERIC.Infrastructure.Persistence.Quiz.QuizRespuestaEntity", b =>
                {
                    b.HasOne("IERIC.SumariosIERIC.Infrastructure.Persistence.Quiz.QuizDesafioEntity", "Desafio")
                        .WithOne("Respuesta")
                        .HasForeignKey("IERIC.SumariosIERIC.Infrastructure.Persistence.Quiz.QuizRespuestaEntity", "QuizDesafioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_QuizRespuesta_QuizDesafio_QuizDesafioId");

                    b.Navigation("Desafio");
                });

            modelBuilder.Entity("IERIC.SumariosIERIC.Infrastructure.Persistence.Quiz.QuizRespuestaOpcionEntity", b =>
                {
                    b.HasOne("IERIC.SumariosIERIC.Infrastructure.Persistence.Quiz.QuizOpcionEntity", "Opcion")
                        .WithMany("RespuestasSeleccionadas")
                        .HasForeignKey("QuizDesafioId", "CodigoOpcion")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_QuizRespuestaOpcion_QuizOpcion");

                    b.HasOne("IERIC.SumariosIERIC.Infrastructure.Persistence.Quiz.QuizRespuestaEntity", "Respuesta")
                        .WithMany("OpcionesSeleccionadas")
                        .HasForeignKey("QuizRespuestaId", "QuizDesafioId")
                        .HasPrincipalKey("Id", "QuizDesafioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_QuizRespuestaOpcion_QuizRespuesta");

                    b.Navigation("Opcion");

                    b.Navigation("Respuesta");
                });

            modelBuilder.Entity("IERIC.SumariosIERIC.Infrastructure.Persistence.Quiz.QuizDesafioEntity", b =>
                {
                    b.Navigation("Opciones");

                    b.Navigation("Respuesta");
                });

            modelBuilder.Entity("IERIC.SumariosIERIC.Infrastructure.Persistence.Quiz.QuizOpcionEntity", b =>
                {
                    b.Navigation("RespuestasSeleccionadas");
                });

            modelBuilder.Entity("IERIC.SumariosIERIC.Infrastructure.Persistence.Quiz.QuizRespuestaEntity", b =>
                {
                    b.Navigation("OpcionesSeleccionadas");
                });

            modelBuilder.Entity("IERIC.SumariosIERIC.Infrastructure.Persistence.Quiz.QuizSesionEntity", b =>
                {
                    b.Navigation("CuilesVinculados");

                    b.Navigation("Desafios");
                });
#pragma warning restore 612, 618
        }
    }
}
