export const MOSTRAR_VALIDACION_TELEFONO = false;

export const INICIAR_EN_INSCRIPCION = false;

export const UBICAR_EMPRESAS_INTEGRANTES_AL_FINAL = true;

export const PERMITIR_SALTEAR_VALIDACIONES = true;
